<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="changelog.xslt"?>
<!DOCTYPE changelog [
	<!ELEMENT changelog (version+,lastupdate)>
	<!ELEMENT version (name, description, features, bugfixes, todo)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT description (#PCDATA)>
	<!ELEMENT features (feature*)>
	<!ELEMENT feature (#PCDATA)>
	<!ELEMENT bugfixes (bugfix*)>
	<!ELEMENT bugfix (#PCDATA)>
	<!ELEMENT todo (#PCDATA)>
	<!ELEMENT lastupdate (#PCDATA)>
]>
<!--/*
 *  ********************************************************************   **
 *  Copyright notice                                                       **
 *  **																	   **
 *  (c) 2003 Entagged Developpement Team				                   **
 *  http://www.sourceforge.net/projects/entagged                           **
 *  **																	   **
 *  All rights reserved                                                    **
 *  **																	   **
 *  This script is part of the Entagged project. The Entagged 			   **
 *  project is free software; you can redistribute it and/or modify        **
 *  it under the terms of the GNU General Public License as published by   **
 *  the Free Software Foundation; either version 2 of the License, or      **
 *  (at your option) any later version.                                    **
 *  **																	   **
 *  The GNU General Public License can be found at                         **
 *  http://www.gnu.org/copyleft/gpl.html.                                  **
 *  **																	   **
 *  This copyright notice MUST APPEAR in all copies of the file!           **
 *  ********************************************************************
 */-->
<changelog>
		<version>
		<name>V0.22 ??/??/????</name>
		
		<description>Maintenance release</description>
		
		<features>
		</features>
		
		<bugfixes>
			<bugfix>Track duration of VBR-Encoded MP3s with a VBRI header is now parsed correctly.</bugfix>
		</bugfixes>
		
		<todo></todo>
	</version>
		<version>
		<name>V0.21 05/02/2006</name>
		
		<description>Maintenance release</description>
		
		<features>
			<feature>Audioformats: Introduced AudioFileModificationListener for global handling of file changes.
			So now one can alter an audio file before its actually modified, or just after it has been modified.
			Because of that the AudioFileIO's and AudioFileWriter's "delete" methods need AudioFile instances
			instead of simple java.io.File instances.</feature>
			<feature>Entagged now allows the preservation of the file modification time.</feature>
			<feature>When the new renaming was released, the track number extension was lost, since that was noticed
			by users, its reimplemented as an option.</feature>
			<feature>The tageditor now supports automatic refresh of the folder content table (activate in "General Options).</feature>
			<feature>Add a new transformtion: capitalize first letter only</feature>
			<feature>Comment fields are written with the language code of the current installation. So on non
			english systems the the windows property page and WMP should display the comment text for ID3V2.
			An already existing comment field will be replaced. If there are more comment fields, the
			first one (random) will be replaced. If one of them is already in the systems language, it will
			be handled as the top field (first field) and will be modified.</feature>
		</features>
		
		<bugfixes>
			<bugfix>Use UTF-16LE by default when using UTF16, or WMP looses his pants</bugfix>
		</bugfixes>
		
		<todo></todo>
	</version>
		<version>
		<name>V0.20 14/09/2005</name>
		
		<description>Maintenance release</description>
		
		<features>
			<feature>Freedb: Using floats for id calculation leads to better results and more perfect matches</feature>
			<feature>Audioformats: Return the precise length as a float with the new getPreciseLength methods</feature>
		</features>
		
		<bugfixes>
			<bugfix>Fixes handling of encoding preferences. The bug resulted in UTF16 being always used</bugfix>
			<bugfix>Deadlock in swing with autocompletion, and more little fixes</bugfix>
		</bugfixes>
		
		<todo></todo>
	</version>
		<version>
		<name>V0.19 02/07/2005</name>
		
		<description>Rename improved, maintance</description>
		
		<features>
			<feature>Allow to choose wether to use UTF16 or ISO for id3 tags</feature>
			<feature>Liree did a spanking new rename function with tree preview and many other goodies</feature>
			<feature>Possibility to use bitrate in directory patterns</feature>			
		</features>
		
		<bugfixes>
			<bugfix>Various little unimportant fixes</bugfix>
		</bugfixes>
		
		<todo></todo>
	</version>
	
	<version>
		<name>V0.18 25/02/2005</name>
		
		<description>Maintenance release</description>
		
		<features>
			<feature>Using Unicode by default for id3 tags, alowing use for rich charsets</feature>
			<feature>audioformats api:Big rewrite, the structure is now more clear for each format</feature>
			<feature>audioformats api:ASF update to handle more cases</feature>
			<feature>audioformats api:OGG fields with no "=" are now handled, plus some other ogg bugfixes</feature>
			<feature>audioformats api:Update of MP3 bitrate and length handling for special mp3's</feature>
			<feature>audioformats api:Some new methods in the audioformats API, lists, etc</feature>
			<feature>Introducing a statistics tool, to view various stats about your collection</feature>
			<feature>Updated translations for french, spanish, english and german</feature>	
			<feature>New transformation added, which will replace non us-ascii characters with underscores, or will try to find a similar us-ascii character to replace with ('ï¿½' will become 'a')</feature>					
		</features>
		
		<bugfixes>
			<bugfix>Using a file pattern that leads to an existing filname can delete the renamed file</bugfix>
			<bugfix>Remove the gridlines on the table</bugfix>
			<bugfix>When renaming files, skip files that have no content for the requested field</bugfix>
			<bugfix>When transforming, capitalizing sometimes ignored previous transformations</bugfix>
		</bugfixes>
		
		<todo></todo>
	</version>
	
	<version>
		<name>V0.17 08/01/2005</name>
		
		<description>Fixes startup for first time users :).</description>
		
		<features>
			<feature>Improved again keyboard edition, with sensible focus changes
					with TAB key, etc, just try it !</feature>
			
		</features>
		
		<bugfixes>
			<bugfix>Fixes the startup error first-time users experienced</bugfix>
			<bugfix>Fixes deletion of id3 tag even if there is some garbage
				between the end of the tag and the beginning of the audio</bugfix>
			<bugfix>Fixes bug that prevented to correclty tag multi-lined comments</bugfix>
			<bugfix>Fixed bug that prevented from writing correct id3v1 tag if no track number set</bugfix>
			<bugfix>Capitalization at new lines too</bugfix>	
		</bugfixes>
		
		<todo></todo>
	</version>
	
	<version>
		<name>V0.16 08/01/2005</name>
		
		<description>Fixes mp3 tagging bug, improves UI a lot.</description>
		
		<features>
			<feature>New transformation added, which will replace / and \ to -</feature>			
			<feature>Autocompleting path field, If not modifying path, a list of parent directories is offerded.</feature>
			<feature>Coloration denote if typed path exists or not.</feature>
			
			<feature>Patterns now have highlighting of valid masks (eg. &lt;artist&gt;).</feature>
			<feature>Navigating through the table with keyboard 
           			 (left or backspace for previous visited directory, 
 			         ALT-Up for parent directory, right for entering directory,
 			         ENTER will enter a single selected directory, if a file or more
 			         than one item is selected, the tag editing panel is selected.)
 			         F5 will perform a reload.</feature>
 			<feature>The pattern fields of "Rename from tag" and "Tag from filename"
 			         do now help with a list of completions if you wait 500 ms after
 			         entering "&lt;"</feature>
			<feature>Manual-Freedb: If freedb offers the track offsets from the cd it is possible
			         to compute the track lengths. If provided the matching dialog warns with yellow
			         background if assigned result differs in duration about more than 2 seconds.
			         Additional there is a new automatic arrangement button.</feature>
		</features>
		
		<bugfixes>
			<bugfix>Listing wizard now takes selected directory as initial directory (if possible)</bugfix>
			<bugfix>Ogg/Flac files weren't recognized as tagged or untagged properly</bugfix>
			<bugfix>Manual-Freedb: The track number is now taken from the freedb result.</bugfix>
			<bugfix>ID3v2 tag was incorrectly overwritten (size should be 10 bytes more).</bugfix>
		</bugfixes>
		
		<todo></todo>
	</version>
	<version>
		<name>V0.15.1 01/01/2005</name>
		
		<description>First release this year :) fixes the ogg corruption bug with some files introduced in 0.15.</description>
		
		<features>
			<feature>None</feature>			
		</features>
		
		<bugfixes>
			<bugfix>Fixes the ogg corruption bug</bugfix>
			<bugfix>Fixes handling of non-standard COMMENT and TRACK fields in ogg files</bugfix>
			<bugfix>The progress dialog closes when nothing wrong hapens</bugfix>
			<bugfix>Improved WMA file handling, some part of the tag were optional but not recognized as such</bugfix>
		</bugfixes>
		
		<todo></todo>
	</version>
	<version>
		<name>V0.15 23/12/2004</name>
		
		<description>Big major UI improvements</description>
		
		<features>
			<feature>Added a Listing generator, that can browse a directory and generate an xml,html,csv listing of all audio files</feature>
			<feature>Multi-lined comments in tags (for tag format that support it)</feature>
			<feature>Added automated Track number enumeration</feature>	
			<feature>GUI improved a lot thanks to Christian !</feature>			
		</features>
		
		<bugfixes>
			<bugfix>Tag fom filename:multiple &lt;ignore&gt; masks, and check for erroneous multiple other masks (there can be no &lt;artist&gt; twice either in dir or filename mask or both)</bugfix>
			<bugfix>Look And feel selection fixed</bugfix>
		
		</bugfixes>
		
		<todo></todo>
	</version>
	<version>
		<name>V0.14 06/12/2004</name>
		
		<description>Adds a manual freedb selection matching dialog, small bugfixes, now supports wma files</description>
		
		<features>
			<feature>audioformats-api: Complete rewrite of the id3v2 tag handling, more object oriented</feature>
			<feature>audioformats-api: new support for tagging wma (version 9)</feature>
			<feature>German language is now available</feature>
			<feature>freedb: connections can now be made through a proxy</feature>
			<feature>manual freedb shows a dialog if there are less selected files than freedb tracks, to choose from.</feature>
			<feature>When entering a directory, the clicked dir is remembered, when clicking parent, the table scrolls to the saved dir, this makes navigation easier</feature>
			<feature>Command line tools: Creation of XML reports and converting them to html or csv using XSL.</feature>
		</features>
		
		<bugfixes>
			<bugfix>audioformats-api: Flac and vorbis tags now save TRACKNUMBER and DESCRIPTiON, instead of TRACK and COMMENT, as requested by the vorbis specs</bugfix>
			<bugfix>Fixed recursive tagging with freedb (wasn't woring at all)</bugfix>
		</bugfixes>
		
		<todo></todo>
	</version>
	<version>
		<name>V0.13 07/11/2004</name>
		
		<description>Big Bugfix !</description>
		
		<features>
			<feature>Very small correction in spanish lang file</feature>
		</features>
		
		<bugfixes>
			<bugfix>Under windows entagged could not write/delete tags because of file locking issues</bugfix>
		</bugfixes>
		
		<todo></todo>
	</version>
	
	<version>
		<name>V0.12 06/11/2004</name>
		
		<description>Minor feature and bugfixes, enjoy</description>
		
		<features>
			<feature>Added tag deletion to the audioformats api</feature>
			<feature>A delete tags button in the tag editor allows to delete tags from the selected files</feature>
		</features>
		
		<bugfixes>
			<bugfix>Fixed a crash when starting entagged and the last working dir do not exists anymore</bugfix>
			<bugfix>Fixed a bug that prevented to properly write ogg tags</bugfix>
		</bugfixes>
		
		<todo></todo>
	</version>
	<version>
		<name>V0.11 30/10/2004</name>
		
		<description></description>
		
		<features>
			<feature>freedb-api: Freedb API has been completely rewritten ! More clear, and adds a full text search feature, through the freedb search page</feature>
			<feature>freedb-api: Get the available http servers</feature>
			<feature>freedb: Manual freedb search instead of requiring the user to manually search freedb allows to search directly within the tag editor</feature>	
			<feature>freedb: Sorts the results of a freedb query ascending by quality, most of the time the last entry listed is the best you can have (based on some guessing about filled values and length of the fields)</feature>
			<feature>freedb: Option panel to set various freedb config (server, etc)</feature>
			<feature>gui: Possibility to clear the list of masks</feature>
			<feature>audioformats-api: Improved support for Id3v2.2 and 2.3, all frame should be kept and rewritten whan a tag is modified</feature>
			<feature>audioformats-api: Added mpc (mp+) support for v7 Stream versions, and APE tags (used also in Monkey Audio)</feature>
			<feature>some more that i just can't remember !</feature>
		</features>
		
		<bugfixes>
			<bugfix>Capitalize didn't work properly, fixed</bugfix>
			<bugfix>Pressing enter on one of the fields is like pressing save (or rename or tag, etc)</bugfix>
			<bugfix>Focus order fixed (mainly) for all the contorl panels (tab-cycle is ok)</bugfix>
			<bugfix>Save the selected transformations across sessions, as well as last used masks and directory pattern selection</bugfix>
			<bugfix>When renaming a file to the same name, except the case, no more error is displayed, but i can't make java to rename case sensitively, so the name stay the same..</bugfix>
			<bugfix>Fixed some little unsigned bytes in he mp3 library</bugfix>
			<bugfix>Fixed some little bugs in the audioformats library (lone tmp files, etc)</bugfix>
		</bugfixes>
		
		<todo>Correct (if they can be found) the remaining bugs in ape, mpc support..</todo>
	</version>
	<version>
		<name>V0.10 20/06/2004</name>
		
		<description>This is a major release, as it fixes many small bugs, and many big bugs, especially in file tagging/renaming in windows, some weird bugs in mp3,ogg and flac tag reading/writing. Interface also changed a bit to become much simpler ! Recursive operations have been implemented, what more do you want ??</description>
		
		<features>
			<feature>Recursive processing: When a directory is selected, all audio files under it are processed</feature>
			<feature>Tag transformations: Uppercase, Capitalize, and many more</feature>
			<feature>Variable text can be ignored when tagging from filename</feature>
			<feature>New file browsing interface. Faster!</feature>
			<feature>Spanish translation</feature>
			<feature>Audio file processing and freedb as separate libraries</feature>		
		</features>
		
		<bugfixes>
			<bugfix>Tag from filename now works on windows :)</bugfix>
			<bugfix>Fixed unclosed files bug</bugfix>
			<bugfix>Fixed lack of resources exception when working with big directories</bugfix>
			<bugfix>Fixed file length detection in some mp3 files with trash</bugfix>
			<bugfix>Fixed ID3v2.3 big tag reading and writting</bugfix>
		</bugfixes>
		
		<todo>Many things .. :)</todo>
	</version>
	
	<version>
		<name>V0.09 14/04/2004</name>
		
		<description>This version is a complete rewrite, so the old changelog doesn't apply anymore</description>
		
		<features>
			<feature>See readme for all (old and) new features</feature>
		</features>
		
		<bugfixes>
			<bugfix>Plenty ? :)</bugfix>
		</bugfixes>
		
		<todo>Now that this is done, new feature will start to be added, with more formats, and who knows what ..</todo>
	</version>
	
	<version>
		<name>V0.08 15/11/2003</name>
		
		<description>After a long quiet period, because I hadn't a lot of time, a quick update to fix some bugs, and nice features added</description>
		
		<features>
			<feature>Option panel, allows to change langage, and track formatting patterns</feature>
			<feature>Track formatting pattern, allows to define how to rename track numbers when renaming from freedb, ex: 14/25 or 13 or "12 foo 24" anything can be done !</feature>
			<feature>Alpha version of the library, it can scan folder show the contents in a tree view, but beside that it can do nothing interesting :)</feature>
		</features>
		
		<bugfixes>
			<bugfix>Corrected ID3v1 bug if track number was not a number, it replace it by 0 now</bugfix>
			<bugfix>many minor bugs that i found, some bugfixes also on mp3 reading/writing</bugfix>
		</bugfixes>
		
		<todo>Working on the html export and other things, searching, etc... by the time you could test the db</todo>
	</version>
	
	<version>
		<name>V0.07 29/09/2003</name>
		
		<description>Minor Bugfixes..</description>
		
		<features>
			<feature>Possible to change the order of the files in the table (instead of filename order), for freedb to work if the files aren't in the correct order</feature>
			<feature>Copying from id3v1/2 to another, now copies the entire tag (even if there are multiples files selected) instead of the text in the fields only</feature>
		</features>
		
		<bugfixes>
			<bugfix>Corrected a bug introduced on v0.06, if a invalid root is chosen (like an empty cdrom or floppy) the program would crash and can't restart, this is fixed</bugfix>
			<bugfix>The dialog are not correctly childed, when the main window goes to back (looses focus) and then come to front, the dialogs are shown.</bugfix>
			<bugfix>Handles the case of the files trying to be writed are read only or you don't have the permission to write, it shows a messages, but don't crash</bugfix>
			<bugfix>Don't crash if freedb return a 200 exact match</bugfix>
			<bugfix>Better handling of the filename -> Tag (reluctant quantifiers in regex) (now works with eg. 01 title (%4 %3)).</bugfix>
			<bugfix>I don't know if it's working, but I forced to use "ISO-8859-1" charset (8bit encoding of each character) to prevent ID3 tag corruption with foreign langage</bugfix>
		</bugfixes>
		
		<todo>Music Library, I Know.. Beside That, a nice option panel...</todo>
	</version>
	
	<version>
		<name>V0.06 24/09/2003</name>
		
		<description>This is a quick fix to make the program run under Linux !!! </description>
		
		<features>
			<feature>It is now possible to toggle the display of the id3v1 or v2 tag in the tag editor table</feature>
			<feature>Generate pls and m3u playlists in the currently selected folder</feature>
			<feature>Now has a toolbar, instead of buttons on the bottom of the window</feature>
		</features>
		
		<bugfixes>
			<bugfix>Freedb bug when the artist name isn't correctly formed, it can now handles with it.</bugfix>
			<bugfix>More Strings are translatable</bugfix>
			<bugfix>Runs Under Linux</bugfix>
		</bugfixes>
		
		<todo></todo>
	</version>
	
	<version>
		<name>V0.05 21/09/2003</name>
		
		<description>This release improve a lot the GUI, with java look and feel's support (a lot of !)</description>
		
		<features>
			<feature>Java look and feels supported (the java ones, plus some other found on www.javootoo.com) and packaged with the release</feature>
			<feature>A preference module now saves the last options selected (the last drive used, the checkboxes, some settings and so on)</feature>
			<feature>Multi-Langage enabled, entagged can now be easily translated ! (operational for the next release)</feature>
			<feature>(experimental) You can rename a file directly in the table, editing the corresponding cell.</feature>
		</features>
		
		<bugfixes>
			<bugfix>Still more bugfixes in the ID3 tag reading, the correct length will now be computed virtually every time, even if the file is a bit damaged..(well at least I hope so :) )</bugfix>
			<bugfix>ID3 tag reading more tolerant with the badly formed id3v2 tags (ie bad length, null padded files with no tag, ..)</bugfix>
			<bugfix>When the program starts, it doesn't check anymore if there is a floppy ! and remembers the last drive used</bugfix>
			<bugfix>When there are no freedb results, the program doesn't crash anymore.</bugfix>
			<bugfix>When saving an empty field, sometimes the program crashes, this is fixed</bugfix>
			<bugfix>The icons are now correct in the Filesystem tree (showing directories with mp3 only as leafs)</bugfix>
			<bugfix>Support the empty id3v1 genre content (0xFF value)</bugfix>
			<bugfix>Some debug values were printed out, this is fixed, now it prints only the user understandable infos</bugfix>
			<bugfix>ID3v2 advanced now shows only the interesting frames</bugfix>
		</bugfixes>
		
		<todo>The MP3 Library will soon appear, we are working hard on it !</todo>
	</version>
	
	<version>
		<name>V0.04 10/09/2003</name>
		
		<description>This release focuses on performance upgrade, the reading/writing routines have been greatly improved</description>
		
		<features>
			<feature>It is now very hard to go faster !! </feature>
			<feature>Added the advanced ID3v2 editing features (this is not finished but the main thing is there)</feature>
			<feature>The Rename funtion with regex</feature>
		</features>
		
		<bugfixes>
			<bugfix>The freedb tagging works with id3v1 and/or id3v2</bugfix>
			<bugfix>The id3v2 tag now overwrites the old one if there is enough room instead of rewriting the whole file</bugfix>
			<bugfix>Plenty of bugs corrected ! (always the same thing :) )</bugfix>
		</bugfixes>
		
		<todo>I think we will focus on the mp3 Library for a moment but this is unsure...</todo>
	</version>
	
	<version>
		<name>V0.03 04/09/2003</name>
		
		<description>There it is ! many GUI improvements, still very far from perfect !</description>
		
		<features>
			<feature>File Renamer is now fully functionnal, though not fool proof, you should use it wisely !</feature>
			<feature>The freedb is now functionnal with a nice GUI, due to a bug, you can only save the id3v2tags</feature>
			<feature>Possibility to copy the ID3v2 from id3v1 and vice versa</feature>
			<feature>Selection of the root directory is now allowed(a little buggy though)</feature>
		</features>
		
		<bugfixes>
			<bugfix>Fixed bugs in the ID3 reader (for the comment field mostly)</bugfix>
			<bugfix>a little more stable in case of bad id3v2 tags, but very perfectible !</bugfix>
		</bugfixes>
		
		<todo>I think the next release will focus mainly on improving the read routine (i'm tired of designing gui for the moment :)</todo>
	</version>
	
	<version>
		<name>V0.02 01/09/2003</name>
		
		<description>Second release a lot of improvemnts in basic stability and an added File Renamer module</description>
		
		<features>
			<feature>Renaming the files of an album with the id3v2 tag and a totally custom mask</feature>
		</features>
		
		<bugfixes>
			<bugfix>Now it can handle with a folder with not only mp3's, it will take only those</bugfix>
			<bugfix>It can also handles the mp3 that haven't been yet tagged</bugfix>
			<bugfix>Some minor bugs that made the program crash are now fixed, this is a general stability improvement.</bugfix>
		</bugfixes>
		
		<todo>This version should really be useable by anyone. I have to fix the hardcoded c:\ drive for the tree root so one can access other drives... I have also to make a better Dialog for the FIle renaming to use the full potential of the module i have written (renaming from tag and tagginf from filename, all with custom patterns...)</todo>
	</version>
	
	<version>
		<name>V0.01 31/08/2003</name>
		
		<description>This is the First working version.: you can save and read id3v1 and id3v2 tags (but i don't recommend doing it with sensitive mp3 :), You can also make a freedb query and write one of the results, but not change it...</description>
		
		<features>
			<feature>Saving raw informations gathered with freedb (no changes are allowed for now)</feature>
			<feature>Saving/Reading id3v1 and id3v2 tags file per file or on multiple selection</feature>
		</features>
		
		<bugfixes>
			<bugfix>Diplay of the time format now its ##:## with zeroes if needed</bugfix>
			<bugfix>Comment in ID3v2 are now saved correctly, with the eng\u0000 langage</bugfix>
			<bugfix>Comment in id3v1 is now working properly, even with freedb and uses a combobox</bugfix>
		</bugfixes>
		
		<todo>For the moment, the main things I plan to do are, a gui for the freedb results, so one can change the results gathered from the freedb to suits his needs, fixing some bugs I encounter :), and maybe for the next release a file renamer based on id3tag with custom pattern renaming...</todo>
	</version>
	
	<lastupdate>$Id: changelog.xml,v 1.1 2007/03/23 14:16:48 nicov1 Exp $</lastupdate>
</changelog>
